"""
Django settings for contratempo project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _carregar_env(caminho):
    """
    Lê o arquivo .env (CHAVE=valor por linha) para os.environ.
    Cada máquina tem o seu .env com as próprias senhas; ele não vai
    junto quando o projeto é copiado. Modelo: .env.exemplo.
    Variáveis já definidas no terminal têm prioridade.
    """
    if not caminho.exists():
        return
    for linha in caminho.read_text(encoding="utf-8").splitlines():
        linha = linha.strip()
        if not linha or linha.startswith("#") or "=" not in linha:
            continue
        chave, valor = linha.split("=", 1)
        os.environ.setdefault(chave.strip(), valor.strip().strip('"').strip("'"))


_carregar_env(BASE_DIR.parent / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Produção x desenvolvimento, controlado pelo .env:
#   DJANGO_DEBUG=0                         -> modo produção (site publicado)
#   DJANGO_ALLOWED_HOSTS=seunome.pythonanywhere.com
#   DJANGO_SECRET_KEY=<chave longa e secreta>
# Sem essas variáveis, vale o modo desenvolvimento (DEBUG ligado).
DEBUG = os.environ.get("DJANGO_DEBUG", "1").strip().lower() in ("1", "true", "sim")

_CHAVE_DESENVOLVIMENTO = "django-insecure-i*pz9sw&-17%74%bn9=u#9egxsehb@is48$z98tiygg+_+d_ps"
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY") or _CHAVE_DESENVOLVIMENTO
if not DEBUG and SECRET_KEY == _CHAVE_DESENVOLVIMENTO:
    from django.core.exceptions import ImproperlyConfigured

    raise ImproperlyConfigured("Em produção (DJANGO_DEBUG=0) defina DJANGO_SECRET_KEY no .env.")

ALLOWED_HOSTS = [h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()]
if DEBUG:
    ALLOWED_HOSTS += ["localhost", "127.0.0.1", "[::1]"]

# Formulários enviados pelo domínio publicado (HTTPS) são aceitos pelo CSRF.
CSRF_TRUSTED_ORIGINS = [f"https://{h.lstrip('.')}" for h in ALLOWED_HOSTS if h not in ("localhost", "127.0.0.1", "[::1]")]

if not DEBUG:
    # O PythonAnywhere entrega o HTTPS por um proxy; este cabeçalho avisa o Django.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # O redirecionamento para HTTPS é feito pelo PythonAnywhere (aba Web >
    # "Force HTTPS"). HSTS fica desligado: o domínio pythonanywhere.com não
    # é seu, e um erro de HSTS trava o acesso ao site por meses.
    SILENCED_SYSTEM_CHECKS = ["security.W004", "security.W008"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'marketplace',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'contratempo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'contratempo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        # Valores vêm do .env (veja .env.exemplo na raiz do projeto).
        "NAME": os.environ.get("DB_NAME", "contratempo_db"),
        "USER": os.environ.get("DB_USER", "root"),
        "PASSWORD": os.environ.get("DB_PASSWORD", ""),
        "HOST": os.environ.get("DB_HOST", "127.0.0.1"),
        "PORT": os.environ.get("DB_PORT", "3306"),
        "OPTIONS": {
            # garante utf8mb4 também na conexão do driver
            "charset": "utf8mb4",
        },
    }
}

# DB_ENGINE=sqlite no .env: usa um arquivo local em vez do MySQL.
# Útil em máquinas sem servidor MySQL (o HeidiSQL também abre esse arquivo).
if os.environ.get("DB_ENGINE", "mysql").lower() == "sqlite":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "contratempo.sqlite3",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"
TIME_ZONE = "America/Sao_Paulo"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'marketplace.Usuario'

"""
Trecho ADICIONAL a inserir em contratempo/contratempo/settings.py
(além do que já foi passado em settings_snippet.py — DATABASES e
AUTH_USER_MODEL). Isto configura onde o Django procura templates e
arquivos estáticos, seguindo a estrutura templates/ e static/ na
raiz do projeto (ao lado de manage.py).
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent  # já existe no settings padrão

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],   # <- adicionar isto
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "marketplace.context_processors.menu_categorias",
                "marketplace.context_processors.carrinho_resumo",
            ],
        },
    },
]

STATIC_URL = "static/"
# Os estáticos ficam em marketplace/static/; uma pasta static/ na raiz é opcional.
STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").exists() else []
STATIC_ROOT = BASE_DIR / "staticfiles"          # <- usado só em produção (collectstatic)

# Em produção, CSS/JS ganham uma "impressão digital" no nome a cada mudança
# (ex.: styles-retro.3f9a1c2b.css), para nenhum navegador ficar preso a uma
# cópia velha em cache. Exige rodar o collectstatic a cada atualização — o
# atualizar.sh já faz isso. Detalhes em marketplace/estaticos.py.
if not DEBUG:
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "marketplace.estaticos.EstaticosComVersao"},
    }

# Uploads (imagens de anúncios e avatares). ProdutoImagem.url_imagem e
# Usuario.avatar guardam a URL pública gerada por default_storage.
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

LOGIN_URL = "login"

# ---------------------------------------------------------------------
# E-MAIL (Gmail SMTP)
# As credenciais vêm de variáveis de ambiente — nunca escreva a senha
# aqui. No Gmail, use uma "senha de app" (Conta Google > Segurança >
# Verificação em duas etapas > Senhas de app), não a senha normal.
#
# Preencha EMAIL_HOST_USER e EMAIL_HOST_PASSWORD no arquivo .env da raiz
# do projeto (ou defina no terminal com $env:EMAIL_HOST_USER = "...").
#
# Sem essas variáveis, os e-mails são impressos no terminal do
# runserver (útil em desenvolvimento para copiar os links).
# ---------------------------------------------------------------------
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "").strip()
# O Google mostra a senha de app em blocos ("abcd efgh ijkl mnop");
# os espaços são removidos para evitar erro de login.
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "").replace(" ", "").strip()

# Brevo (brevo.com): usado quando há BREVO_API_KEY no .env. Necessário no
# PythonAnywhere grátis, onde o Gmail recusa o login vindo do servidor.
# O remetente continua sendo EMAIL_HOST_USER, que precisa estar confirmado
# no Brevo. Detalhes em marketplace/email_brevo.py.
BREVO_API_KEY = os.environ.get("BREVO_API_KEY", "").strip()

if BREVO_API_KEY:
    EMAIL_BACKEND = "marketplace.email_brevo.BrevoEmailBackend"
    EMAIL_TIMEOUT = 20
elif EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = "smtp.gmail.com"
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_TIMEOUT = 15
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

DEFAULT_FROM_EMAIL = f"contratempo <{EMAIL_HOST_USER or 'nao-responda@contratempo.local'}>"

# Validade dos links de confirmação de cadastro e de nova senha (3 dias).
PASSWORD_RESET_TIMEOUT = 60 * 60 * 24 * 3

# Mostra no terminal do runserver os erros do app (ex.: falha de e-mail).
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "loggers": {"marketplace": {"handlers": ["console"], "level": "INFO", "propagate": False}},
}
# ---------------------------------------------------------------------
# contratempo/urls.py — arquivo do projeto (não do app marketplace)
# ---------------------------------------------------------------------
"""
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("marketplace.urls")),
]

handler404 = "marketplace.views_errors.pagina_nao_encontrada"
"""