# Generated by Django 5.2.17 on 2026-09-30 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_dados_iniciais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(choices=[('falsificado', 'Produto falsificado ou pirata'), ('proibido', 'Item proibido ou ilegal'), ('enganoso', 'Descrição ou fotos enganosas'), ('golpe', 'Suspeita de golpe'), ('ofensivo', 'Conteúdo ofensivo'), ('outro', 'Outro motivo')], max_length=15)),
                ('descricao', models.TextField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('procedente', 'Procedente (anúncio encerrado)'), ('improcedente', 'Improcedente')], default='pendente', max_length=15)),
                ('data_denuncia', models.DateTimeField(auto_now_add=True)),
                ('data_analise', models.DateTimeField(blank=True, null=True)),
                ('produto', models.ForeignKey(db_column='produto_id', on_delete=django.db.models.deletion.CASCADE, related_name='denuncias', to='marketplace.produto')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_feitas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Denúncia',
                'verbose_name_plural': 'Denúncias',
                'db_table': 'denuncias',
                'ordering': ['-data_denuncia'],
            },
        ),
    ]
